on: [push]
name: CI
jobs:
  test:
    strategy:
      matrix:
        ruby-version: [2.6, 2.7, 3.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - run: bundle exec rake test

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        go-version: 3.0.x
    - run: bundle exec rubocop
